### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by TierreAsh** [SGZ-Creations/Power-Armour-Replacer#1]
PAR Library in Factorio requires version of Power Armour Replacer which is not yet on mod portal which makes my save unplayeble:(  I will loose armor if i load it now.

**Comment by SGZ-Creations** [comment]
Hey the update version u are looking for are currently in beta on my discord witch u can find link on the factorio mod portal. I know i did the versioning bad like that still on purpose to my beta version of P.A.R 

Anyway here u go Note this is beta can still go bad just reverted a Nanobot bug.
[par_lib_0.1.8.zip](https://github.com/SGZ-Creations/Power-Armour-Replacer/files/11930154/par_lib_0.1.8.zip)
[Power-Armour-Replacer_0.1.34.zip](https://github.com/SGZ-Creations/Power-Armour-Replacer/files/11930155/Power-Armour-Replacer_0.1.34.zip)


The other option is to go back a version.

Thanks for the report. and the like for the mod.

**Comment by TierreAsh** [comment]
![изображение](https://github.com/SGZ-Creations/Power-Armour-Replacer/assets/90751011/4c5d8a87-e4d2-4b20-a894-e2a885f7f85d)
Didn't work....

**Comment by SGZ-Creations** [comment]
Would recommend load a version back.

**Comment by SGZ-Creations** [comment]
A fix will be on my discord shortly. I'm trying to keep all at one place thanks a lot for the reports.
